services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - apache
      - websocket
    networks:
      - app-network
    restart: unless-stopped

  apache:
    build: .
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      DB_HOSTNAME: mysql
      DB_USERNAME: root
      DB_PASSWORD: rootpass
      DB_NAME: db_spotifry_clone
      DB_PORT: 3306
      SMTP_USER: gmail account
      SMTP_PASSWORD: gmail app password
    networks:
      - app-network
    expose:
      - "80"

  websocket:
    build: .
    command: php listen/server/chat-server.php
    volumes:
      - .:/var/www/html
    environment:
      DB_HOSTNAME: mysql
      DB_USERNAME: root
      DB_PASSWORD: rootpass
      DB_NAME: db_spotifry_clone
    networks:
      - app-network
    expose:
      - "8080"

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: db_spotifry_clone
    volumes:
       - mysql_data:/var/lib/mysql
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: